---
info:
  description: Spring Cloud Config Repo
  url: https://github.com/spring-cloud-samples
eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://10.254.1.122}/eureka/
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
logging:
  level:
     io:
        pivotal: DEBUG
     com:
        netflix: WARN

endpoints:
   health:
     sensitive: false
     
spring:
   zipkin:
      host: opsmgr.vert.fe.gopivotal.com
      port: 9410
---
spring:
  profiles: cloud
eureka:
  instance:
     nonSecurePort: 80

---
spring:
  profiles: local
eureka:
  instance:
    nonSecurePort: ${server.port}
