---
info:
  description: Spring Cloud Config Repo
  url: https://github.com/spring-cloud-samples
eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}

logging:
  level:
     io:
        pivotal: DEBUG
     com:
        netflix: WARN

endpoints:
   health:
     sensitive: false

spring:
   zipkin:
      host: opsmgr.vert.fe.gopivotal.com
      port: 9410
